affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 10
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 6
symbolic.funs_name.0:
- - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
symbolic.funs_name.1:
- - x
  - x
  - x
symbolic_enabled: false
width:
- - 6
  - 0
- - 3
  - 0
- - 1
  - 0
